"""delete cascade

Revision ID: 02e071d874b6
Revises: 94f3e1d4eaea
Create Date: 2024-05-25 11:34:33.485164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e071d874b6'
down_revision: Union[str, None] = '94f3e1d4eaea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('danger_for_system_danger_id_fkey', 'danger_for_system', type_='foreignkey')
    op.create_foreign_key(None, 'danger_for_system', 'dangers', ['danger_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'danger_for_system', type_='foreignkey')
    op.create_foreign_key('danger_for_system_danger_id_fkey', 'danger_for_system', 'dangers', ['danger_id'], ['id'])
    # ### end Alembic commands ###
