"""initial migration

Revision ID: 2c0b57536597
Revises: 
Create Date: 2024-05-07 15:52:17.216413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0b57536597'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('danger_for_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_system_id', sa.Integer(), nullable=True),
    sa.Column('danger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['danger_id'], ['danger.id'], ),
    sa.ForeignKeyConstraint(['ship_system_id'], ['ship_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ship_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_system_id'], ['ship_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ship_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_system_id'], ['ship_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability')
    op.drop_table('protection')
    op.drop_table('security_indicator')
    op.drop_table('equipment')
    op.drop_table('danger_for_system')
    op.drop_table('ship_system')
    op.drop_table('ship')
    op.drop_table('danger')
    # ### end Alembic commands ###
