"""initial

Revision ID: 30a45d9d077a
Revises: 
Create Date: 2024-05-15 00:37:08.050577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a45d9d077a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dangers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('danger_for_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_system_id', sa.Integer(), nullable=True),
    sa.Column('danger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['danger_id'], ['dangers.id'], ),
    sa.ForeignKeyConstraint(['ship_system_id'], ['ship_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ship_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_system_id'], ['ship_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_and_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('ship_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.ForeignKeyConstraint(['ship_system_id'], ['ship_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_and_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_system_id', sa.Integer(), nullable=True),
    sa.Column('security_indicator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['security_indicator_id'], ['security_indicators.id'], ),
    sa.ForeignKeyConstraint(['ship_system_id'], ['ship_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_and_equipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_system_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.ForeignKeyConstraint(['ship_system_id'], ['ship_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerabilities')
    op.drop_table('system_and_equipments')
    op.drop_table('protections')
    op.drop_table('system_and_indicators')
    op.drop_table('ship_and_systems')
    op.drop_table('equipments')
    op.drop_table('danger_for_system')
    op.drop_table('ships')
    op.drop_table('ship_systems')
    op.drop_table('security_indicators')
    op.drop_table('dangers')
    # ### end Alembic commands ###
