"""add shipsystem properties

Revision ID: a85c5a79b1f4
Revises: 30a45d9d077a
Create Date: 2024-05-22 11:34:10.049298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85c5a79b1f4'
down_revision: Union[str, None] = '30a45d9d077a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ship_systems', sa.Column('category', sa.Integer(), nullable=False))
    op.add_column('ship_systems', sa.Column('document', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ship_systems', 'document')
    op.drop_column('ship_systems', 'category')
    # ### end Alembic commands ###
