"""delete cascade all

Revision ID: b9f28b7325cf
Revises: 02e071d874b6
Create Date: 2024-05-25 11:38:34.088684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f28b7325cf'
down_revision: Union[str, None] = '02e071d874b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('danger_for_system_ship_system_id_fkey', 'danger_for_system', type_='foreignkey')
    op.create_foreign_key(None, 'danger_for_system', 'ship_systems', ['ship_system_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('equipments_ship_system_id_fkey', 'equipments', type_='foreignkey')
    op.create_foreign_key(None, 'equipments', 'ship_systems', ['ship_system_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('protections_equipment_id_fkey', 'protections', type_='foreignkey')
    op.create_foreign_key(None, 'protections', 'equipments', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ship_and_systems_ship_id_fkey', 'ship_and_systems', type_='foreignkey')
    op.drop_constraint('ship_and_systems_ship_system_id_fkey', 'ship_and_systems', type_='foreignkey')
    op.create_foreign_key(None, 'ship_and_systems', 'ship_systems', ['ship_system_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ship_and_systems', 'ships', ['ship_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('system_and_equipments_equipment_id_fkey', 'system_and_equipments', type_='foreignkey')
    op.drop_constraint('system_and_equipments_ship_system_id_fkey', 'system_and_equipments', type_='foreignkey')
    op.create_foreign_key(None, 'system_and_equipments', 'equipments', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'system_and_equipments', 'ship_systems', ['ship_system_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('system_and_indicators_security_indicator_id_fkey', 'system_and_indicators', type_='foreignkey')
    op.drop_constraint('system_and_indicators_ship_system_id_fkey', 'system_and_indicators', type_='foreignkey')
    op.create_foreign_key(None, 'system_and_indicators', 'ship_systems', ['ship_system_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'system_and_indicators', 'security_indicators', ['security_indicator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('vulnerabilities_equipment_id_fkey', 'vulnerabilities', type_='foreignkey')
    op.create_foreign_key(None, 'vulnerabilities', 'equipments', ['equipment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vulnerabilities', type_='foreignkey')
    op.create_foreign_key('vulnerabilities_equipment_id_fkey', 'vulnerabilities', 'equipments', ['equipment_id'], ['id'])
    op.drop_constraint(None, 'system_and_indicators', type_='foreignkey')
    op.drop_constraint(None, 'system_and_indicators', type_='foreignkey')
    op.create_foreign_key('system_and_indicators_ship_system_id_fkey', 'system_and_indicators', 'ship_systems', ['ship_system_id'], ['id'])
    op.create_foreign_key('system_and_indicators_security_indicator_id_fkey', 'system_and_indicators', 'security_indicators', ['security_indicator_id'], ['id'])
    op.drop_constraint(None, 'system_and_equipments', type_='foreignkey')
    op.drop_constraint(None, 'system_and_equipments', type_='foreignkey')
    op.create_foreign_key('system_and_equipments_ship_system_id_fkey', 'system_and_equipments', 'ship_systems', ['ship_system_id'], ['id'])
    op.create_foreign_key('system_and_equipments_equipment_id_fkey', 'system_and_equipments', 'equipments', ['equipment_id'], ['id'])
    op.drop_constraint(None, 'ship_and_systems', type_='foreignkey')
    op.drop_constraint(None, 'ship_and_systems', type_='foreignkey')
    op.create_foreign_key('ship_and_systems_ship_system_id_fkey', 'ship_and_systems', 'ship_systems', ['ship_system_id'], ['id'])
    op.create_foreign_key('ship_and_systems_ship_id_fkey', 'ship_and_systems', 'ships', ['ship_id'], ['id'])
    op.drop_constraint(None, 'protections', type_='foreignkey')
    op.create_foreign_key('protections_equipment_id_fkey', 'protections', 'equipments', ['equipment_id'], ['id'])
    op.drop_constraint(None, 'equipments', type_='foreignkey')
    op.create_foreign_key('equipments_ship_system_id_fkey', 'equipments', 'ship_systems', ['ship_system_id'], ['id'])
    op.drop_constraint(None, 'danger_for_system', type_='foreignkey')
    op.create_foreign_key('danger_for_system_ship_system_id_fkey', 'danger_for_system', 'ship_systems', ['ship_system_id'], ['id'])
    # ### end Alembic commands ###
